### ISSUE TITLE
Selenium wd is reporting errors

### ISSUE THREAD

**Issue by zakhenry** [spira/spira#278]
See below for output, likely a dependency has been updated and is failing compatibility with something. Possibly fixable by version locking.

```
The command "gulp test" exited with 0.
0.44s$ ./node_modules/.bin/cucumber.js --tags ~@ignore
/home/travis/build/spira/spira/node_modules/selenium-webdriver/_base.js:104
        vm.runInContext(opt_srcText, closure, src);
           ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/home/travis/build/spira/spira/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/home/travis/build/spira/spira/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/home/travis/build/spira/spira/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
The command "./node_modules/.bin/cucumber.js --tags ~@ignore" exited with 8.
```

**Comment by zakhenry** [comment]
Closed in #279
